/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}", 
    "./modules/**/*.{js,jsx,ts,tsx}",
    "./modules/**/**/*.{js,jsx,ts,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        dark: {
          asideColor: '#191919',
          iconsColor: '#AEAEAE',
          asideTextColor: '#8C8C8C',
          activeTab: '#202020',
          homeText: '#8B8B8B',
          optionsTab: '#2A2A2A',
          chatsBarColor: '#202020',
          chatsMessageUnread: '#1D1178',
          chatsBarItemColor: '#272727',
          chatsBarTextColor: '#c5c5c5',
          chatsBarActiveButtonTextColor: '#58A0FD',
          chatsBarActiveButtonColor: '#2B2A2E',
          chatsBarActiveContainerMessageColor: '#353438',
          chatsBarButtonTextColor: '#8C8C8C',
          chatsBarButtonColor: '#242424',
          chatsBarContainerMessageColor: '#303030',
          callsBarTextColor: '#909090',
          callsBarCallNameColor: '#FFFFFF',
          callsBarCallDateColor: '#8C8C8C',
          callsCalendarDateColor: '#9B9B9B',
          callsCalendarDayColor: '#1C1C1C',
          callsCalendarCallColor: '#2C2C2C',
          callsCalendarActiveCallColor: '#2B3644',
          callsCalendarCallTextColor: '#BEB8D1',
          callsCalendarActiveCallTextColor: '#58A0FD',
          callsCalendarActiveDayColor: '#252525',
          storiesBarMenuTextColor: '#FFFFFF',
          storiesBarMenuButtonBgColor: '#2C2A2E',
          createModalHoverColorButton: '#303031',
          createModalTextColorButton: '#D9D9D9',
          callsModalHeaderColor: '#151515',
          myMessageColor: '#2D2B32',
          pinnedMessage: '#1D1D1E',
          pinnedMessageTextColor: '#9F84FD',
          voiceMessageColor: '#3B3846',
        },
        light: {
          asideColor: '#FFFFFF',
          iconsColor: '#666666',
          asideTextColor: '#4C4C4C',
          activeTab: '#F0F0F0',
          homeText: '#4B4B4B',
          optionsTab: '#EAEAEA',
          chatsBarColor: '#F7F7F7',
          chatsMessageUnread: '#3A88E0',
          chatsBarItemColor: '#EFEFEF',
          chatsBarTextColor: '#5C5C5C',
          chatsBarActiveButtonTextColor: '#3178FD',
          chatsBarActiveButtonColor: '#E3E3E3',
          chatsBarActiveContainerMessageColor: '#DADADA',
          chatsBarButtonTextColor: '#7C7C7C',
          chatsBarButtonColor: '#F0F0F0',
          chatsBarContainerMessageColor: '#E5E5E5',
          callsBarTextColor: '#6C6C6C',
          callsBarCallNameColor: '#000000',
          callsBarCallDateColor: '#5C5C5C',
          callsCalendarDateColor: '#4A4A4A',
          callsCalendarDayColor: '#EFEFEF',
          callsCalendarCallColor: '#E3E3E3',
          callsCalendarActiveCallColor: '#DADADA',
          callsCalendarCallTextColor: '#4A4A4A',
          callsCalendarActiveCallTextColor: '#2178E0',
          callsCalendarActiveDayColor: '#CFCFCF',
          storiesBarMenuTextColor: '#000000',
          storiesBarMenuButtonBgColor: '#F0F0F0',
          createModalHoverColorButton: '#E5E5E5',
          createModalTextColorButton: '#2D2D2D',
          callsModalHeaderColor: '#FFFFFF',
          myMessageColor: '#F9F9F9',
          pinnedMessage: '#F5F5F5',
          pinnedMessageTextColor: '#6161FD',
          voiceMessageColor: '#EFEFEF',
        },
      },
    },
  },
  plugins: [],
};
